Repository PackageFoundation/yap, pull requests merged in 2022-01, with the labels that each got.

#3 feat: environment variables resolution
  resolver/resolver.go
Labels: enhancement

#5 chore: add goreleaser integration
  .github/workflows/goreleaser.yaml
Labels: chore

#16 feat(ci): enable preliminary docker.io and GHCR support (closes #6 #12)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/discussion-issue-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/docker-image.yml
  .pre-commit-config.yaml
  cmd/root.go
  constants/constants.go
  docker/amazon-1/Dockerfile
  docker/amazon-2/Dockerfile
  docker/arch/Dockerfile
  docker/centos-8/Dockerfile
  docker/debian-buster/Dockerfile
  docker/debian-jessie/Dockerfile
  docker/debian-stretch/Dockerfile
  docker/fedora-35/Dockerfile
  docker/opensuse-tubleweed/Dockerfile
  docker/oracle-8/Dockerfile
  docker/rocky-8/Dockerfile
  docker/ubuntu-bionic/Dockerfile
  docker/ubuntu-focal/Dockerfile
  images/yap.svg
Labels: bug, enhancement, chore
